name: Simple Manual Workflow - Three Env

on:
  workflow_dispatch:

jobs:

  DEV-JOB:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "I am running a job in the Dev environment"
          echo "It's my secret ${{ secrets.MY_SECRET }}"
          echo "It's my another secret ${{ secrets.ANOTHER_SECRET }}"

  QA-JOB:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV-JOB

    steps:
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "I am running a job in the QA environment"

  PROD-JOB:
    runs-on: ubuntu-latest
    environment: PROD
#    needs: QA-JOB

    steps:
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "I am running a job in the PROD environment"
